!function(a){"function"==typeof define&&define.amd?define(["jquery"],a):"object"==typeof exports?module.exports=a(require("jquery")):a(jQuery)}(function(a){function i(){var b,c,d={height:f.innerHeight,width:f.innerWidth};return d.height||(b=e.compatMode,(b||!a.support.boxModel)&&(c="CSS1Compat"===b?g:e.body,d={height:c.clientHeight,width:c.clientWidth})),d}function j(){return{top:f.pageYOffset||g.scrollTop||e.body.scrollTop,left:f.pageXOffset||g.scrollLeft||e.body.scrollLeft}}function k(){if(b.length){var e=0,f=a.map(b,function(a){var b=a.data.selector,c=a.$element;return b?c.find(b):c});for(c=c||i(),d=d||j();e<b.length;e++)if(a.contains(g,f[e][0])){var h=a(f[e]),k={height:h[0].offsetHeight,width:h[0].offsetWidth},l=h.offset(),m=h.data("inview");if(!d||!c)return;l.top+k.height>d.top&&l.top<d.top+c.height&&l.left+k.width>d.left&&l.left<d.left+c.width?m||h.data("inview",!0).trigger("inview",[!0]):m&&h.data("inview",!1).trigger("inview",[!1])}}}var c,d,h,b=[],e=document,f=window,g=e.documentElement;a.event.special.inview={add:function(c){b.push({data:c,$element:a(this),element:this}),!h&&b.length&&(h=setInterval(k,250))},remove:function(a){for(var c=0;c<b.length;c++){var d=b[c];if(d.element===this&&d.data.guid===a.guid){b.splice(c,1);break}}b.length||(clearInterval(h),h=null)}},a(f).on("scroll resize scrollstop",function(){c=d=null}),!g.addEventListener&&g.attachEvent&&g.attachEvent("onfocusin",function(){d=null})});

function ParamsMap(a){this.hashMap={};this.size=0;if(a){a=a.split("&");for(var b=0;b<a.length;b++){var c=a[b].split("=");this.put(c[0],c[1])}}}ParamsMap.prototype.put=function(a,b){var c=new ParamsEntry(a,b);this.hashMap[a]=c;this.hashMap[this.size++]=c};ParamsMap.prototype.get=function(a){return(a=this.hashMap[a])?a.getParamValue():null};
ParamsMap.prototype.toUrl=function(){for(var a="?",b=0;b<this.size;b++)var c=this.hashMap[b],a=a+c.getParamName()+"="+escape(encodeURI(c.getParamValue()))+"&";return a=a+"dummy="+(new Date).getTime()};function ParamsEntry(a,b){this.paramName=a;this.paramValue=b}ParamsEntry.prototype.getParamName=function(){return this.paramName};ParamsEntry.prototype.getParamValue=function(){return this.paramValue};
function sendAjaxRequest(a,b,c,e){void 0==e&&(e=!0);a+=b.toUrl();$.ajax({type:"GET",url:a,async:e,success:function(a){c(a)},error:function(a){alert(a)}})}
function crossDomainAjax(a,b){if("XDomainRequest"in window&&null!==window.XDomainRequest){var c=new XDomainRequest;c.open("get",a);c.onload=function(){var a=new ActiveXObject("Microsoft.XMLDOM"),d=$.parseJSON(c.responseText);a.async=!1;if(null==d||"undefined"==typeof d)d=$.parseJSON(data.firstChild.textContent);b(d)};c.onerror=function(){_result=!1};c.send()}else{if(-1!=navigator.userAgent.indexOf("MSIE")&&8>parseInt(navigator.userAgent.match(/MSIE ([\d.]+)/)[1],10))return!1;$.ajax({type:"GET",url:a,
success:function(a){b(a)},dataType:"JSON"})}};

/*
 jQuery Placeholder Plugin v2.3.0
 https://github.com/mathiasbynens/jquery-placeholder

 Copyright 2011, 2015 Mathias Bynens
 Released under the MIT license
*/
(function(c){"function"===typeof define&&define.amd?define(["jquery"],c):"object"===typeof module&&module.exports?c(require("jquery")):c(jQuery)})(function(c){function q(b){var a={},d=/^jQuery\d+$/;c.each(b.attributes,function(b,c){c.specified&&!d.test(c.name)&&(a[c.name]=c.value)});return a}function h(b,a){var d=c(this);if(this.value===d.attr("placeholder")&&d.hasClass(f.customClass))if(this.value="",d.removeClass(f.customClass),d.data("placeholder-password")){d=d.hide().nextAll('input[type="password"]:first').show().attr("id",
d.removeAttr("id").data("placeholder-id"));if(!0===b)return d[0].value=a;d.focus()}else this==m()&&this.select()}function l(b){var a=c(this),d=this.id;if(!b||"blur"!==b.type||!a.hasClass(f.customClass))if(""===this.value){if("password"===this.type){if(!a.data("placeholder-textinput")){try{var e=a.clone().prop({type:"text"})}catch(r){e=c("<input>").attr(c.extend(q(this),{type:"text"}))}e.removeAttr("name").data({"placeholder-enabled":!0,"placeholder-password":a,"placeholder-id":d}).bind("focus.placeholder",
h);a.data({"placeholder-textinput":e,"placeholder-id":d}).before(e)}this.value="";a=a.removeAttr("id").hide().prevAll('input[type="text"]:first').attr("id",a.data("placeholder-id")).show()}else if(b=a.data("placeholder-password"))b[0].value="",a.attr("id",a.data("placeholder-id")).show().nextAll('input[type="password"]:last').hide().removeAttr("id");a.addClass(f.customClass);a[0].value=a.attr("placeholder")}else a.removeClass(f.customClass)}function m(){try{return document.activeElement}catch(b){}}
var g="[object OperaMini]"===Object.prototype.toString.call(window.operamini),k="placeholder"in document.createElement("input")&&!g&&!0,g="placeholder"in document.createElement("textarea")&&!g&&!0,n=c.valHooks,p=c.propHooks,f={};if(k&&g){var e=c.fn.placeholder=function(){return this};e.input=!0;e.textarea=!0}else e=c.fn.placeholder=function(b){f=c.extend({},{customClass:"placeholder"},b);return this.filter((k?"textarea":":input")+"[placeholder]").not("."+f.customClass).not(":radio, :checkbox, :hidden").bind({"focus.placeholder":h,
"blur.placeholder":l}).data("placeholder-enabled",!0).trigger("blur.placeholder")},e.input=k,e.textarea=g,e={get:function(b){var a=c(b),d=a.data("placeholder-password");return d?d[0].value:a.data("placeholder-enabled")&&a.hasClass(f.customClass)?"":b.value},set:function(b,a){var d=c(b);if(""!==a){var e=d.data("placeholder-textinput");var g=d.data("placeholder-password");e?(h.call(e[0],!0,a)||(b.value=a),e[0].value=a):g&&(h.call(b,!0,a)||(g[0].value=a),b.value=a)}if(!d.data("placeholder-enabled"))return b.value=
a,d;""===a?(b.value=a,b!=m()&&l.call(b)):(d.hasClass(f.customClass)&&h.call(b),b.value=a);return d}},k||(n.input=e,p.value=e),g||(n.textarea=e,p.value=e),c(function(){c(document).delegate("form","submit.placeholder",function(){var b=c("."+f.customClass,this).each(function(){h.call(this,!0,"")});setTimeout(function(){b.each(l)},10)})}),c(window).bind("beforeunload.placeholder",function(){var b=!0;try{"javascript:void(0)"===document.activeElement.toString()&&(b=!1)}catch(a){}b&&c("."+f.customClass).each(function(){this.value=
""})})});

(function(c){c.fn.niceSelect=function(e){function f(a){a.after(c("<div></div>").addClass("nice-select").addClass(a.attr("class")||"").addClass(a.attr("disabled")?"disabled":"").attr("tabindex",a.attr("disabled")?null:"0").html('<span class="current"></span><ul class="list"></ul>'));var b=a.next(),d=a.find("option");a=a.find("option:selected");b.find(".current").html(a.data("display")||a.text());d.each(function(a){a=c(this);var d=a.data("display");b.find("ul").append(c("<li></li>").attr("data-value",
a.val()).attr("data-display",d||null).addClass("option"+(a.is(":selected")?" selected":"")+(a.is(":disabled")?" disabled":"")).html(a.text()))})}if("string"==typeof e)return"update"==e?this.each(function(){var a=c(this),b=c(this).next(".nice-select"),d=b.hasClass("open");b.length&&(b.remove(),f(a),d&&a.next().trigger("click"))}):"destroy"==e?(this.each(function(){var a=c(this),b=c(this).next(".nice-select");b.length&&(b.remove(),a.css("display",""))}),0==c(".nice-select").length&&c(document).off(".nice_select")):
console.log('Method "'+e+'" does not exist.'),this;this.hide();this.each(function(){var a=c(this);a.next().hasClass("nice-select")||f(a)});c(document).off(".nice_select");c(document).on("click.nice_select",".nice-select",function(a){a=c(this);c(".nice-select").not(a).removeClass("open");a.toggleClass("open");a.hasClass("open")?(a.find(".option"),a.find(".focus").removeClass("focus"),a.find(".selected").addClass("focus")):a.focus()});c(document).on("click.nice_select",function(a){0===c(a.target).closest(".nice-select").length&&
c(".nice-select").removeClass("open").find(".option")});c(document).on("click.nice_select",".nice-select .option:not(.disabled)",function(a){a=c(this);var b=a.closest(".nice-select");b.find(".selected").removeClass("selected");a.addClass("selected");var d=a.data("display")||a.text();b.find(".current").text(d);b.prev("select").val(a.data("value")).trigger("change")});c(document).on("keydown.nice_select",".nice-select",function(a){var b=c(this),d=c(b.find(".focus")||b.find(".list .option.selected"));
if(32==a.keyCode||13==a.keyCode)return b.hasClass("open")?d.trigger("click"):b.trigger("click"),!1;if(40==a.keyCode)return b.hasClass("open")?(a=d.nextAll(".option:not(.disabled)").first(),0<a.length&&(b.find(".focus").removeClass("focus"),a.addClass("focus"))):b.trigger("click"),!1;if(38==a.keyCode)return b.hasClass("open")?(a=d.prevAll(".option:not(.disabled)").first(),0<a.length&&(b.find(".focus").removeClass("focus"),a.addClass("focus"))):b.trigger("click"),!1;if(27==a.keyCode)b.hasClass("open")&&
b.trigger("click");else if(9==a.keyCode&&b.hasClass("open"))return!1});e=document.createElement("a").style;e.cssText="pointer-events:auto";"auto"!==e.pointerEvents&&c("html").addClass("no-csspointerevents");return this}})(jQuery);

